/**
 * Frontend S3 upload utilities.
 *
 * All uploads go through presigned URLs generated by the backend.
 * No AWS credentials are stored or used on the frontend.
 *
 * Flow:
 *   1. Frontend calls backend  →  POST /api/uploads/presign  → gets { uploadUrl, key }
 *   2. Frontend PUTs the file directly to S3 using that URL
 *   3. Frontend notifies backend  →  POST /api/uploads/confirm  → backend saves the key
 */

import api from '@/services/api';
import { toast } from 'sonner';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface UploadResult {
  key: string;
  url: string;
  fileName: string;
  contentType: string;
  size: number;
}

export interface UploadOptions {
  /** Max file size in MB. Default: 10 */
  maxSizeMB?: number;
  /** Allowed MIME types. If omitted, all types are accepted. */
  allowedTypes?: string[];
  /** Progress callback (0–100) */
  onProgress?: (progress: number) => void;
}

export interface MultiUploadResult {
  successful: UploadResult[];
  failed: { file: File; error: string }[];
}

interface PresignApiResponse {
  status: boolean;
  message: string;
  object: {
    uploadUrl: string;
    key: string;
    publicUrl: string;
  };
}

// ─── Constants ────────────────────────────────────────────────────────────────

export const ALLOWED_IMAGE_TYPES = ['image/jpeg', 'image/png', 'image/webp', 'image/gif'];
export const ALLOWED_VIDEO_TYPES = ['video/mp4', 'video/quicktime', 'video/webm', 'video/avi'];
export const ALLOWED_DOCUMENT_TYPES = [
  'application/pdf',
  'application/msword',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
];

// ─── Validation ───────────────────────────────────────────────────────────────

const validateFile = (file: File, options?: UploadOptions): void => {
  const maxSizeMB = options?.maxSizeMB ?? 10;
  if (file.size > maxSizeMB * 1024 * 1024) {
    throw new Error(`"${file.name}" exceeds the ${maxSizeMB} MB size limit`);
  }
  if (options?.allowedTypes?.length && !options.allowedTypes.includes(file.type)) {
    throw new Error(`File type "${file.type}" is not supported`);
  }
};

// ─── Core: presign → PUT → confirm ───────────────────────────────────────────

const presignAndUpload = async (
  file: File,
  folder: string,
  options?: UploadOptions,
  userId?: string,
): Promise<UploadResult> => {
  // 1. Get presigned URL from backend
  const { object: { uploadUrl, key, publicUrl } } = await api.post<PresignApiResponse>('/uploads/presign', {
    fileName: file.name,
    contentType: file.type,
    fileSize: file.size,
    folder,
  });

  // 2. PUT directly to S3 (no auth header — presigned URL is self-authenticating)
  await new Promise<void>((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('PUT', uploadUrl);
    xhr.setRequestHeader('Content-Type', file.type);

    xhr.upload.onprogress = (e) => {
      if (e.lengthComputable) {
        options?.onProgress?.(Math.round((e.loaded / e.total) * 100));
      }
    };

    xhr.onload = () => (xhr.status >= 200 && xhr.status < 300 ? resolve() : reject(new Error(`S3 upload failed: ${xhr.status}`)));
    xhr.onerror = () => reject(new Error('Network error during upload'));
    xhr.send(file);
  });

  // 3. Notify backend that upload is complete — response contains presigned GET URL
  const confirmRes = await api.post<{ status: boolean; object: string | null }>('/uploads/confirm', { key, ...(userId ? { userId } : {}) });
  const viewUrl = confirmRes.object || publicUrl;

  options?.onProgress?.(100);
  toast.success("Uploaded successfully!");
  return {
    key,
    url: viewUrl,
    fileName: file.name,
    contentType: file.type,
    size: file.size,
  };
};

// ─── Upload: Single File ──────────────────────────────────────────────────────

export const uploadSingleFile = async (
  file: File,
  folder: string = 'uploads',
  options?: UploadOptions,
): Promise<UploadResult> => {
  validateFile(file, options);
  return presignAndUpload(file, folder, options);
};

// ─── Upload: Profile Image ────────────────────────────────────────────────────

export const uploadProfileImage = async (
  file: File,
  userId?: string,
): Promise<UploadResult> => {
  validateFile(file, { maxSizeMB: 5, allowedTypes: ALLOWED_IMAGE_TYPES });
  return presignAndUpload(file, `profiles/${userId ?? 'unknown'}`, { maxSizeMB: 5, allowedTypes: ALLOWED_IMAGE_TYPES }, userId);
};

// ─── Upload: Multiple Files ───────────────────────────────────────────────────

export const uploadMultipleFiles = async (
  files: File[],
  folder: string = 'uploads',
  options?: UploadOptions,
): Promise<MultiUploadResult> => {
  const settled = await Promise.allSettled(
    files.map((file) => uploadSingleFile(file, folder, options)),
  );

  const successful: UploadResult[] = [];
  const failed: { file: File; error: string }[] = [];

  settled.forEach((result, i) => {
    if (result.status === 'fulfilled') {
      successful.push(result.value);
    } else {
      failed.push({ file: files[i], error: result.reason?.message ?? 'Upload failed' });
    }
  });

  return { successful, failed };
};

// ─── Upload: Images Only ──────────────────────────────────────────────────────

export const uploadImages = async (
  files: File[],
  folder: string = 'images',
  maxSizeMB = 10,
): Promise<MultiUploadResult> => {
  return uploadMultipleFiles(files, folder, { allowedTypes: ALLOWED_IMAGE_TYPES, maxSizeMB });
};

// ─── Upload: Videos Only ──────────────────────────────────────────────────────

export const uploadVideos = async (
  files: File[],
  folder: string = 'videos',
  maxSizeMB = 500,
): Promise<MultiUploadResult> => {
  return uploadMultipleFiles(files, folder, { allowedTypes: ALLOWED_VIDEO_TYPES, maxSizeMB });
};

// ─── Upload: Documents ────────────────────────────────────────────────────────

export const uploadDocuments = async (
  files: File[],
  folder: string = 'documents',
  maxSizeMB = 50,
): Promise<MultiUploadResult> => {
  return uploadMultipleFiles(files, folder, { allowedTypes: ALLOWED_DOCUMENT_TYPES, maxSizeMB });
};

// ─── Delete ───────────────────────────────────────────────────────────────────

export const deleteFile = async (key: string): Promise<void> => {
  await api.delete(`/uploads/${encodeURIComponent(key)}`);
};
