export const ROUTES = {
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  UPDATE_PASSWORD: '/update-password',
  DASHBOARD: '/dashboard',
  PROJECTS: '/projects',
  PROJECT_CREATE: '/projects/create',
  PROJECT_DETAIL: '/projects/:id',
  INSPECTIONS: '/inspections',
  CHECKLISTS: '/checklists',
  DEFECTS: '/defects',
  REPORTS: '/reports',
  SETTINGS: '/settings',
  ORGANISATION: '/organisation',
  ORGANISATION_DETAIL: '/organisation/:uuid',
  ORGANISATION_ONBOARDING: '/organisation/onboarding',
  ORGANISATION_CREATE: '/organisation/create',
  SUBSCRIPTIONS: '/subscriptions',
  USERS: '/users',
  PROFILE: '/profile',
  FRANCHISE: '/franchise',
  FRANCHISE_SUBSCRIPTIONS: '/franchise-subscriptions',
  CLIENTS: '/clients',
  USERS_ROLES: '/users-roles',
  NOTIFICATIONS: '/notifications',
  UNAUTHORIZED: '/unauthorized',
} as const;

export type RouteKey = keyof typeof ROUTES;
export type RoutePath = (typeof ROUTES)[RouteKey];
